### ISSUE TITLE
[Bug] Official WMPO coffee P=128 checkpoint yields 0% success rate during evaluation

### ISSUE THREAD

**Issue by lzhuohang** [WM-PO/WMPO#11]
Hi, thanks for the great work!

I'm trying to reproduce the reported ~60% success rate for the coffee task (P=128) using the official checkpoint(https://huggingface.co/fangqi/WMPO/tree/main/checkpoint_files/WMPO_models/coffee/P_128):

However, I consistently get 0% success rate during evaluation.

### Environment
- Followed the official setup (Python 3.11, Torch 2.5.1)
- Using `examples/mimicgen/coffee/evaluate.sh` (modified paths only)

### Key code
```bash
set -x

export NCCL_DEBUG=WARN 
export TF_CPP_MIN_LOG_LEVEL=3
export WANDB_API_KEY='' #TODO: use your own WANDB_API_KEY
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export TOKENIZERS_PARALLELISM=true
export CUDA_LAUNCH_BLOCKING=1
export TORCH_USE_CUDA_DSA=1

PROJECT_NAME='WMPO-mimicgen'
EXPERIMENT_NAME='coffee_eval'

TASK_NAME="coffee"
UNNORM_KEY="$TASK_NAME"_d0_300_demos

TARGET_MODEL_PATH="./WMPO/checkpoint_files/WMPO_models/coffee/P_128"
REWARD_MODEL_PATH="./WMPO/checkpoint_files/reward_models/videomae_coffee.pth"

rm "$TARGET_MODEL_PATH"/config.json.back* || true 
rm "$TARGET_MODEL_PATH"/modeling_prismatic.py.back* || true

cp ./WMPO/checkpoint_files/modeling_prismatic.py "$TARGET_MODEL_PATH/"
cp ./WMPO/checkpoint_files/preprocessor_config.json "$TARGET_MODEL_PATH/"
cp ./WMPO/checkpoint_files/processing_prismatic.py "$TARGET_MODEL_PATH/"


CKPT_PATH="./WMPO/checkpoint_files"
VLA_NAME="openvla-oft"
# Evaluate with 4*8 GPUs as default
NUM_NODES=1
NUM_GPUS_PER_NODE=8
export CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7}
export MUJOCO_GL=egl
export PYOPENGL_PLATFORM=egl
unset MUJOCO_EGL_DEVICE_ID
export RAY_TMPDIR=/tmp/ray_wmpo
export LD_LIBRARY_PATH=/root/.mujoco/mujoco210/bin:${LD_LIBRARY_PATH}
NUM_GPUS=$((NUM_NODES * NUM_GPUS_PER_NODE))
ALIGN_PATH="./align.json"



HYDRA_FULL_ERROR=1 python -m verl.trainer.main_ppo \
    +data.task_name=$TASK_NAME \
    data.n_samples=8 \
    data.filter_accuracy=True \
    data.accuracy_lower_bound=0.1 \
    data.accuracy_upper_bound=0.9 \
    data.oversample_factor=1 \
    data.train_batch_size=64 \
    data.val_batch_size=128 \
    data.max_prompt_length=256 \
    data.max_response_length=128 \
    +data.rollout_batch_size=128 \
    +actor_rollout_ref.rollout_base_dir=./tmp_files/rollout_$EXPERIMENT_NAME \
    actor_rollout_ref.model.path=$TARGET_MODEL_PATH \
    actor_rollout_ref.model.vla=$VLA_NAME \
    actor_rollout_ref.model.action_token_len=7 \
    actor_rollout_ref.model.action_chunks_len=8 \
    actor_rollout_ref.actor.optim.lr=5e-6 \
    actor_rollout_ref.actor.optim.warmup_style=constant \
    actor_rollout_ref.actor.ppo_mini_batch_size=128 \
    actor_rollout_ref.actor.ppo_micro_batch_size=$NUM_GPUS \
    actor_rollout_ref.actor.use_dynamic_bsz=False \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.grad_offload=True \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.actor.grad_clip=1 \
    actor_rollout_ref.actor.clip_ratio_high=0.28 \
    actor_rollout_ref.actor.clip_ratio_low=0.2 \
    actor_rollout_ref.actor.num_images_in_input=1 \
    actor_rollout_ref.actor.traj_mini_batch_size=16 \
    actor_rollout_ref.model.enable_gradient_checkpointing=False \
    actor_rollout_ref.model.use_remove_padding=False \
    actor_rollout_ref.actor.entropy_coeff=0. \
    actor_rollout_ref.rollout.num_images_in_input=1 \
    actor_rollout_ref.rollout.val_micro_batch_size=8 \
    actor_rollout_ref.rollout.temperature=1.6 \
    actor_rollout_ref.rollout.experiment_name=$EXPERIMENT_NAME \
    actor_rollout_ref.rollout.micro_batch_size=2 \
    actor_rollout_ref.rollout.unnorm_key=$UNNORM_KEY \
    actor_rollout_ref.rollout.model_family=openvla \
    actor_rollout_ref.rollout.num_steps_wait=10 \
    actor_rollout_ref.rollout.pretrained_checkpoint=$TARGET_MODEL_PATH \
    actor_rollout_ref.rollout.center_crop=True \
    actor_rollout_ref.rollout.max_prompt_length=512 \
    actor_rollout_ref.rollout.log_prob_micro_batch_size=32 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=hf \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.9 \
    actor_rollout_ref.ref.log_prob_micro_batch_size=32 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    actor_rollout_ref.wm.inference_config_path=./WMPO/checkpoint_files/world_models/coffee/P_128/inference_cfg.py \
    actor_rollout_ref.wm.train_config_path=./WMPO/checkpoint_files/world_models/coffee/P_128/train_mimicgen_cfg.py \
    +actor_rollout_ref.wm.update_wm=False \
    actor_rollout_ref.wm.reward_model_path=$REWARD_MODEL_PATH \
    actor_rollout_ref.wm.rm_threshold=0.82 \
    actor_rollout_ref.wm.rm_img_size=224 \
    +actor_rollout_ref.wm.rm_lr=1e-4 \
    +actor_rollout_ref.wm.rm_batch_size=64 \
    +actor_rollout_ref.wm.rm_val_batch_size=512 \
    +actor_rollout_ref.wm.rm_num_workers=8 \
    +actor_rollout_ref.wm.wm_training_steps_per_epoch=10000 \
    +actor_rollout_ref.wm.rm_training_steps_per_epoch=10000 \
    actor_rollout_ref.wm.enable=False \
    algorithm.kl_ctrl.kl_coef=0.00 \
    +trainer.rollout_before_train=False \
    trainer.logger=['console','wandb'] \
    trainer.project_name=$PROJECT_NAME \
    trainer.experiment_name=$EXPERIMENT_NAME \
    trainer.default_local_dir=$CKPT_PATH/$PROJECT_NAME/$EXPERIMENT_NAME \
    trainer.n_gpus_per_node=$NUM_GPUS_PER_NODE \
    trainer.nnodes=$NUM_NODES \
    trainer.save_freq=1 \
    trainer.test_freq=1 \
    trainer.total_epochs=100 \
    trainer.val_only=True \
    +trainer.sim_rollout_epoch=1 \
    algorithm.adv_estimator=grpo \
    algorithm.adv_params.verifier_gamma=1.0 \
    algorithm.adv_params.reward_model_gamma=1.0 \
    trainer.runtime_env=$ALIGN_PATH \
    trainer.wandb_mode=online \
    trainer.val_before_train=True \
```

### Result

<img width="520" height="168" alt="Image" src="https://github.com/user-attachments/assets/3e60756f-c3d6-46e2-8b9f-a5edecdfc5e4" />

num_eval_episodes=128
num_success_episodes=0
success_rate=0.000

### Questions

1. Is `unnorm_key=coffee_d0_300_demos` correct for the P=128 checkpoint?
2. Should evaluation be done with `wm.enable=True` or False?
3. What temperature is used for reporting results in the paper?
4. Are there any additional preprocessing steps required?

Thanks in advance!

**Comment by Violit-hub** [comment]
I encountered the same problem.
I tried the coffee and stackthree tasks, but the success rate was 0% for both SFTmodel and wmpomodel.
I attempted to train my own model using the code "dependencies/openvla-oft/train_coffee.sh", and when tested with the same script, it achieved a success rate of over 30%.

**Comment by fangqi-Zhu** [comment]
1. Yes
2. False
3. As used in the code
4. No

Please refer to https://github.com/WM-PO/WMPO/issues/9#issuecomment-3971148636
The performance fluctuations may be due to the random seed, but a 0% success rate is likely caused by an environment configuration issue. Based on https://github.com/WM-PO/WMPO/issues/9#issuecomment-3971148636, it appears that the 0% success rate is an environment configuration problem. Please check your environment setup and try training the model yourself from wm.

**Comment by lzhuohang** [comment]
> I encountered the same problem. I tried the coffee and stackthree tasks, but the success rate was 0% for both SFTmodel and wmpomodel. I attempted to train my own model using the code "dependencies/openvla-oft/train_coffee.sh", and when tested with the same script, it achieved a success rate of over 30%.

Thanks for sharing your results!

Just to confirm — your ~30% success rate comes from a model trained with
`openvla-oft/train_coffee.sh`, right?

In your evaluation:

* did you use `wm.enable=False` (policy only), or `True` (with world model rollout)?

Also, did you use the same `unnorm_key` (`coffee_d0_300_demos`)?

Thanks a lot！

**Comment by Violit-hub** [comment]
> > I encountered the same problem. I tried the coffee and stackthree tasks, but the success rate was 0% for both SFTmodel and wmpomodel. I attempted to train my own model using the code "dependencies/openvla-oft/train_coffee.sh", and when tested with the same script, it achieved a success rate of over 30%.
> 
> Thanks for sharing your results!
> 
> Just to confirm — your ~30% success rate comes from a model trained with , right?`openvla-oft/train_coffee.sh`
> 
> In your evaluation:
> 
> * did you use  (policy only), or  (with world model rollout)?`wm.enable=False``True`
> 
> Also, did you use the same ()?`unnorm_key``coffee_d0_300_demos`
> 
> Thanks a lot！

Yes.`openvla-oft/train_coffee.sh`

Both True and False have been tried, and the parameter `wm.enable` seems to have no effect on the evaluation.

Yes,I use the same `unnorm_key`.

By the way, any solutions or clues for the 0-success-rate issue?This is my environment：
- Python: 3.11.15
- PyTorch: 2.8.0+cu128
- Torch CUDA build: 12.8
- torchvision: 0.23.0+cu128
- torchaudio: 2.8.0+cu128
- transformers: 4.51.3
- tokenizers: 0.21.4
- tensorflow: 2.19.0
- tensorflow-datasets: 4.9.9
- ray: 2.54.0
- robomimic: reported 0.3.1 when imported from editable path
- robomimic package listing: 0.3.0
- robosuite package listing: 1.4.1
- mimicgen package listing: 1.0.0
- mujoco: 3.6.0
- mujoco-py: 2.1.2.14
- numpy: 1.26.4
- scipy: 1.17.1
- scikit-learn: 1.8.0
- timm: 0.9.16
- peft: 0.11.0
- diffusers: 0.29.0
- flash-attn: 2.8.2
- xformers: 0.0.32.post2
- tensordict: 0.11.0
- webdataset: 1.0.2
Due to equipment limitations, this is the closest environment I can set up to match the project's recommended settings.

**Comment by Waxmell114514** [comment]
Hi, and thank you very much for sharing the full environment details — this is very helpful.

I reproduced the official coffee checkpoints and got non-zero results:

- coffee P=128: 53.1% in my setup, vs. 61.7% reported in the paper
- coffee P=1280: 73.4% in my setup, vs. 75.0% reported in the paper

So the released checkpoints do not seem to be universally broken. The absolute success rate can shift across environments and random seeds, but in a fixed environment we can reproduce the expected improvement trend consistently (for example, P=1280 > P=128 in the same setup).

Comparing the failing environment above with a working one, a few differences look especially important:

- `torch / torchvision / torchaudio`: `2.8.0 / 0.23.0 / 2.8.0` with CUDA `12.8`, while the repo is much closer to the `2.5.1` line
- `transformers / tokenizers`: `4.51.3 / 0.21.4`, while the OpenVLA code path in this repo explicitly expects the `4.40.1 / 0.19.1` line
- `mujoco`: `3.6.0`, while the repo scripts are built around MuJoCo `2.1.0` (`~/.mujoco/mujoco210`) with `mujoco-py==2.1.2.14`
- `robomimic`: imported as `0.3.1` but listed as `0.3.0`, which suggests the environment may not be fully clean/consistent

Because of this, my current guess is that the 0% result is more likely caused by environment drift / incomplete pinning than by a faulty checkpoint.

A good next step would be to re-test in a fresh environment aligned as closely as possible to the repo path, especially:

- Python `3.11.x`
- `torch==2.5.1`, `torchvision==0.20.1`, `torchaudio==2.5.1`
- `moojink/transformers-openvla-oft` on the `4.40.1` line
- `tokenizers==0.19.1`
- `huggingface-hub < 1.0`
- MuJoCo `2.1.0` + `mujoco-py==2.1.2.14`
- clean reinstall of `robosuite / robomimic / mimicgen / robosuite-task-zoo / LIBERO`
- `PYTHONNOUSERSITE=1` to avoid user-site packages shadowing the conda environment

Especially, I think the version of MuJoCo is really crucial.

If useful, I can also share the exact install script / environment summary that worked for me.

<img width="1459" height="138" alt="Image" src="https://github.com/user-attachments/assets/c526f136-b6c5-474e-b93a-a0594194c9b0" />


<img width="1442" height="198" alt="Image" src="https://github.com/user-attachments/assets/4b61173d-2648-47da-9559-6c9d38c28d7f" />

**Comment by Violit-hub** [comment]
> Hi, and thank you very much for sharing the full environment details — this is very helpful.
> 
> I reproduced the official coffee checkpoints and got non-zero results:
> 
> * coffee P=128: 53.1% in my setup, vs. 61.7% reported in the paper
> * coffee P=1280: 73.4% in my setup, vs. 75.0% reported in the paper
> 
> So the released checkpoints do not seem to be universally broken. The absolute success rate can shift across environments and random seeds, but in a fixed environment we can reproduce the expected improvement trend consistently (for example, P=1280 > P=128 in the same setup).
> 
> Comparing the failing environment above with a working one, a few differences look especially important:
> 
> * `torch / torchvision / torchaudio`:  with CUDA , while the repo is much closer to the  line`2.8.0 / 0.23.0 / 2.8.0``12.8``2.5.1`
> * `transformers / tokenizers`: , while the OpenVLA code path in this repo explicitly expects the  line`4.51.3 / 0.21.4``4.40.1 / 0.19.1`
> * `mujoco`: , while the repo scripts are built around MuJoCo  () with `3.6.0``2.1.0``~/.mujoco/mujoco210``mujoco-py==2.1.2.14`
> * `robomimic`: imported as  but listed as , which suggests the environment may not be fully clean/consistent`0.3.1``0.3.0`
> 
> Because of this, my current guess is that the 0% result is more likely caused by environment drift / incomplete pinning than by a faulty checkpoint.
> 
> A good next step would be to re-test in a fresh environment aligned as closely as possible to the repo path, especially:
> 
> * Python `3.11.x`
> * `torch==2.5.1`, , `torchvision==0.20.1``torchaudio==2.5.1`
> * `moojink/transformers-openvla-oft` on the  line`4.40.1`
> * `tokenizers==0.19.1`
> * `huggingface-hub < 1.0`
> * MuJoCo `2.1.0` + `mujoco-py==2.1.2.14`
> * clean reinstall of `robosuite / robomimic / mimicgen / robosuite-task-zoo / LIBERO`
> * `PYTHONNOUSERSITE=1` to avoid user-site packages shadowing the conda environment
> 
> Especially, I think the version of MuJoCo is really crucial.
> 
> If useful, I can also share the exact install script / environment summary that worked for me.
> 
> <img alt="Image" width="1459" height="138" src="https://private-user-images.githubusercontent.com/232729665/581314712-c526f136-b6c5-474e-b93a-a0594194c9b0.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzcwODY0MzksIm5iZiI6MTc3NzA4NjEzOSwicGF0aCI6Ii8yMzI3Mjk2NjUvNTgxMzE0NzEyLWM1MjZmMTM2LWI2YzUtNDc0ZS1iOTNhLWEwNTk0MTk0YzliMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDQyNVQwMzAyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTgwY2Y3MmVhZjFiZDMzNDZhZDE3N2Q1YWRjNTY5ZWFiNmI5MDNkNzU2YjU0ZGJiMjE5Mjk1NDc4ODc0ZmVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.g6N9yNwE-P88LQac7mXCrfdHi-2JbZ4eLni2cyzdtmU"> <img alt="Image" width="1442" height="198" src="https://private-user-images.githubusercontent.com/232729665/581314713-4b61173d-2648-47da-9559-6c9d38c28d7f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzcwODY0MzksIm5iZiI6MTc3NzA4NjEzOSwicGF0aCI6Ii8yMzI3Mjk2NjUvNTgxMzE0NzEzLTRiNjExNzNkLTI2NDgtNDdkYS05NTU5LTZjOWQzOGMyOGQ3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDQyNVQwMzAyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDE2YmQ5MWY5ZTU4YzM1NDBkNzUyNGFjNTNkZmUxNDBkZTVjZGZmNjc3MDMyZDQzYTI3YmZkZjQ1Mzk5MjVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.Sfjap2FyAkZ6bhtAitq5xrnL6c5fblbzXqzd24pQKag">

I tried again and still 0%.If you can provide install script / environment summary, I think it would be of great help.
```=== WMPO environment summary ===
python: 3.11.15 (main, Mar 11 2026, 17:20:07) [GCC 14.3.0]
python_executable: /root/miniconda3/envs/wmpo/bin/python
PYTHONNOUSERSITE: None
MUJOCO_PY_MUJOCO_PATH: /root/.mujoco/mujoco210

torch_cuda_available: True
torch_cuda_build: 12.4
gpu_name: NVIDIA H800 PCIe
gpu_capability: (9, 0)

torch: 2.5.1
  path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/torch/__init__.py
torchvision: 0.20.1
  path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/torchvision/__init__.py
torchaudio: 2.5.1
  path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/torchaudio/__init__.py
transformers: 4.40.1
  path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/transformers/__init__.py
tokenizers: 0.19.1
  path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/tokenizers/__init__.py
huggingface-hub: 0.36.2
  path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/huggingface_hub/__init__.py
numpy: 1.26.4
  path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/numpy/__init__.py
tensorflow: 2.19.0
  path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/tensorflow/__init__.py
tensorflow-datasets: 4.9.9
  path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/tensorflow_datasets/__init__.py
timm: 0.9.10
  path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/timm/__init__.py
peft: 0.11.0
  path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/peft/__init__.py
diffusers: 0.33.0
  path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/diffusers/__init__.py
xformers: 0.0.28.post3
  path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/xformers/__init__.py
flash-attn: 2.5.5
  path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/flash_attn/__init__.py
tensordict: 0.12.2
  path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/tensordict/__init__.py
torchdata: 0.11.0
  path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/torchdata/__init__.py
ray: 2.55.1
  path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/ray/__init__.py
wandb: 0.26.1
  path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/wandb/__init__.py
mujoco: 3.7.0
  path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/mujoco/__init__.py
mujoco-py: 2.1.2.14
  path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/mujoco_py/__init__.py
robosuite: 1.4.1
  path: /WMPO/dependencies/robosuite/robosuite/__init__.py
robomimic: 0.3.0
  path: /WMPO/dependencies/robomimic/robomimic/__init__.py
mimicgen: 1.0.0
  path: /WMPO/dependencies/mimicgen/mimicgen/__init__.py
robosuite_task_zoo: 0.1
  path: /WMPO/dependencies/robosuite-task-zoo/robosuite_task_zoo/__init__.py
colossalai: 0.4.7
  path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/colossalai/__init__.py
tensornvme: 0.1.0
  path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/tensornvme/__init__.py
apex: 0.1
  path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/apex/__init__.py
=== end ===
```
I noticed a problem when reconfiguring the environment，It seems there are two types of Mujoco：MuJoCo 2.1.0 + mujoco-py==2.1.2.14 and mujoco: 3.7.0.
```MUJOCO_PY_MUJOCO_PATH: /root/.mujoco/mujoco210 
mujoco: 3.7.0 path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/mujoco/__init__.py 
mujoco-py: 2.1.2.14 path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/mujoco_py/__init__.py
```
Do you mean "mujoco210 + mujoco-py: 2.1.2.14" by "MuJoCo 2.1.0 + mujoco-py==2.1.2.14"?The requirements.txt file does not specify the version of Mujoco，When I run `pip install -r requirements.txt`, it automatically installs `mujoco: 3.7.0` for me.

**Comment by Waxmell114514** [comment]
> > Hi, and thank you very much for sharing the full environment details — this is very helpful.
> > I reproduced the official coffee checkpoints and got non-zero results:
> > 
> > * coffee P=128: 53.1% in my setup, vs. 61.7% reported in the paper
> > * coffee P=1280: 73.4% in my setup, vs. 75.0% reported in the paper
> > 
> > So the released checkpoints do not seem to be universally broken. The absolute success rate can shift across environments and random seeds, but in a fixed environment we can reproduce the expected improvement trend consistently (for example, P=1280 > P=128 in the same setup).
> > Comparing the failing environment above with a working one, a few differences look especially important:
> > 
> > * `torch / torchvision / torchaudio`:  with CUDA , while the repo is much closer to the  line`` 2.8.0 / 0.23.0 / 2.8.0``12.8``2.5.1 ``
> > * `transformers / tokenizers`: , while the OpenVLA code path in this repo explicitly expects the  line`` 4.51.3 / 0.21.4``4.40.1 / 0.19.1 ``
> > * `mujoco`: , while the repo scripts are built around MuJoCo  () with `` 3.6.0``2.1.0``~/.mujoco/mujoco210``mujoco-py==2.1.2.14 ``
> > * `robomimic`: imported as  but listed as , which suggests the environment may not be fully clean/consistent`` 0.3.1``0.3.0 ``
> > 
> > Because of this, my current guess is that the 0% result is more likely caused by environment drift / incomplete pinning than by a faulty checkpoint.
> > A good next step would be to re-test in a fresh environment aligned as closely as possible to the repo path, especially:
> > 
> > * Python `3.11.x`
> > * `torch==2.5.1`, , `` torchvision==0.20.1``torchaudio==2.5.1 ``
> > * `moojink/transformers-openvla-oft` on the  line`4.40.1`
> > * `tokenizers==0.19.1`
> > * `huggingface-hub < 1.0`
> > * MuJoCo `2.1.0` + `mujoco-py==2.1.2.14`
> > * clean reinstall of `robosuite / robomimic / mimicgen / robosuite-task-zoo / LIBERO`
> > * `PYTHONNOUSERSITE=1` to avoid user-site packages shadowing the conda environment
> > 
> > Especially, I think the version of MuJoCo is really crucial.
> > If useful, I can also share the exact install script / environment summary that worked for me.
> > <img alt="Image" width="1459" height="138" src="https://private-user-images.githubusercontent.com/232729665/581314712-c526f136-b6c5-474e-b93a-a0594194c9b0.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzcwODY0MzksIm5iZiI6MTc3NzA4NjEzOSwicGF0aCI6Ii8yMzI3Mjk2NjUvNTgxMzE0NzEyLWM1MjZmMTM2LWI2YzUtNDc0ZS1iOTNhLWEwNTk0MTk0YzliMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDQyNVQwMzAyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTgwY2Y3MmVhZjFiZDMzNDZhZDE3N2Q1YWRjNTY5ZWFiNmI5MDNkNzU2YjU0ZGJiMjE5Mjk1NDc4ODc0ZmVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.g6N9yNwE-P88LQac7mXCrfdHi-2JbZ4eLni2cyzdtmU"> <img alt="Image" width="1442" height="198" src="https://private-user-images.githubusercontent.com/232729665/581314713-4b61173d-2648-47da-9559-6c9d38c28d7f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzcwODY0MzksIm5iZiI6MTc3NzA4NjEzOSwicGF0aCI6Ii8yMzI3Mjk2NjUvNTgxMzE0NzEzLTRiNjExNzNkLTI2NDgtNDdkYS05NTU5LTZjOWQzOGMyOGQ3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDQyNVQwMzAyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDE2YmQ5MWY5ZTU4YzM1NDBkNzUyNGFjNTNkZmUxNDBkZTVjZGZmNjc3MDMyZDQzYTI3YmZkZjQ1Mzk5MjVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.Sfjap2FyAkZ6bhtAitq5xrnL6c5fblbzXqzd24pQKag">
> 
> I tried again and still 0%.If you can provide install script / environment summary, I think it would be of great help.
> 
> ```
> python: 3.11.15 (main, Mar 11 2026, 17:20:07) [GCC 14.3.0]
> python_executable: /root/miniconda3/envs/wmpo/bin/python
> PYTHONNOUSERSITE: None
> MUJOCO_PY_MUJOCO_PATH: /root/.mujoco/mujoco210
> 
> torch_cuda_available: True
> torch_cuda_build: 12.4
> gpu_name: NVIDIA H800 PCIe
> gpu_capability: (9, 0)
> 
> torch: 2.5.1
>   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/torch/__init__.py
> torchvision: 0.20.1
>   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/torchvision/__init__.py
> torchaudio: 2.5.1
>   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/torchaudio/__init__.py
> transformers: 4.40.1
>   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/transformers/__init__.py
> tokenizers: 0.19.1
>   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/tokenizers/__init__.py
> huggingface-hub: 0.36.2
>   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/huggingface_hub/__init__.py
> numpy: 1.26.4
>   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/numpy/__init__.py
> tensorflow: 2.19.0
>   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/tensorflow/__init__.py
> tensorflow-datasets: 4.9.9
>   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/tensorflow_datasets/__init__.py
> timm: 0.9.10
>   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/timm/__init__.py
> peft: 0.11.0
>   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/peft/__init__.py
> diffusers: 0.33.0
>   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/diffusers/__init__.py
> xformers: 0.0.28.post3
>   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/xformers/__init__.py
> flash-attn: 2.5.5
>   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/flash_attn/__init__.py
> tensordict: 0.12.2
>   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/tensordict/__init__.py
> torchdata: 0.11.0
>   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/torchdata/__init__.py
> ray: 2.55.1
>   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/ray/__init__.py
> wandb: 0.26.1
>   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/wandb/__init__.py
> mujoco: 3.7.0
>   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/mujoco/__init__.py
> mujoco-py: 2.1.2.14
>   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/mujoco_py/__init__.py
> robosuite: 1.4.1
>   path: /WMPO/dependencies/robosuite/robosuite/__init__.py
> robomimic: 0.3.0
>   path: /WMPO/dependencies/robomimic/robomimic/__init__.py
> mimicgen: 1.0.0
>   path: /WMPO/dependencies/mimicgen/mimicgen/__init__.py
> robosuite_task_zoo: 0.1
>   path: /WMPO/dependencies/robosuite-task-zoo/robosuite_task_zoo/__init__.py
> colossalai: 0.4.7
>   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/colossalai/__init__.py
> tensornvme: 0.1.0
>   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/tensornvme/__init__.py
> apex: 0.1
>   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/apex/__init__.py
> === end ===
> ```
> 
> I noticed a problem when reconfiguring the environment，It seems there are two types of Mujoco：MuJoCo 2.1.0 + mujoco-py==2.1.2.14 and mujoco: 3.7.0.
> 
> ```
> mujoco: 3.7.0 path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/mujoco/__init__.py 
> mujoco-py: 2.1.2.14 path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/mujoco_py/__init__.py
> ```
> 
> Do you mean "mujoco210 + mujoco-py: 2.1.2.14" by "MuJoCo 2.1.0 + mujoco-py==2.1.2.14"?The requirements.txt file does not specify the version of Mujoco，When I run `pip install -r requirements.txt`, it automatically installs `mujoco: 3.7.0` for me.

[install_superpod_full_wmpo.sh](https://github.com/user-attachments/files/27080779/install_superpod_full_wmpo.sh)

Thanks — your latest environment summary is very helpful.

Yes: by “MuJoCo 2.1.0 + mujoco-py==2.1.2.14”, I mean the native MuJoCo 2.1.0 runtime unpacked at `~/.mujoco/mujoco210`, together with the Python binding `mujoco-py==2.1.2.14`.

This is separate from the PyPI package `mujoco`. Since `requirements.txt` does not pin the `mujoco` version, `pip install -r requirements.txt` can indeed install a newer wheel such as `mujoco==3.7.0`. So yes, an environment can contain both:
- native runtime: `~/.mujoco/mujoco210`
- `mujoco-py==2.1.2.14`
- and also a newer PyPI `mujoco` package

When I referred to “MuJoCo 2.1.0”, I meant the native runtime used by `mujoco-py`, not the version reported by `import mujoco`.

For reference, below are the key environment summary and the install script (which may not apply to you, just for reference) from the setup that produced my non-zero results (`53.1%` for coffee P=128 and `73.4%` for coffee P=1280):

```bash
=== working WMPO environment summary ===
python: 3.11.x
PYTHONNOUSERSITE=1

torch==2.5.1
torchvision==0.20.1
torchaudio==2.5.1

transformers==4.40.1
# installed from moojink/transformers-openvla-oft
tokenizers==0.19.1
huggingface-hub==0.31.1

numpy==1.26.4
tensorflow==2.19.0
timm==0.9.16
peft==0.11.0
diffusers==0.33.0
xformers==0.0.28.post3
flash-attn==2.5.5

MUJOCO_PY_MUJOCO_PATH=~/.mujoco/mujoco210
LD_LIBRARY_PATH includes ~/.mujoco/mujoco210/bin
native MuJoCo runtime: 2.1.0
mujoco-py==2.1.2.14

editable dependencies:
robosuite @ b9d8d3de5e3dfd1724f4a0e6555246c460407daa
robomimic @ d0b37cf214bd24fb590d182edb6384333f67b661
robosuite-task-zoo @ 74eab7f88214c21ca1ae8617c2b2f8d19718a9ed
mimicgen (editable)
LIBERO (editable)
=== end ===

**Comment by Violit-hub** [comment]
> > > 你好，非常感谢你分享完整的环境细节——这非常有帮助。我复刻了官方咖啡检查点，结果都不是零：
> > > 
> > > * 咖啡P=128：我的设备中占53.1%，而论文中报道的比例为61.7%
> > > * 咖啡P=1280：我的设备中占73.4%，而论文中报道的75.0%
> > > 
> > > 因此，发布的检查点似乎并非普遍失效。绝对成功率会在不同环境和随机种子间发生变化，但在固定环境中，我们可以一致重现预期的改进趋势（例如，在同一设置下，P=1280 > P=128）。将上述失败环境与工作环境进行比较，有几个差异显得尤为重要：
> > > 
> > > * `torch / torchvision / torchaudio`： 与CUDA共度，而回购则更接近该行12.8` 2.8.0 / 0.23.0 / 2.8.0``2.5.1 `
> > > * `transformers / tokenizers`： ，而该仓库中的OpenVLA代码路径明确期望为line4.40.1 / 0.19.1 “'` 4.51.3 / 0.21.4`
> > > * `mujoco`： ，而仓库脚本则围绕MuJoCo（）构建，2.1.0mujoco-py==2.1.2.14 ''` 3.6.0``~/.mujoco/mujoco210`
> > > * `robomimic`： 导入为 但被列为 ，这表明环境可能并不完全干净/一致 0.3.0 “”` 0.3.1`
> > > 
> > > 因此，我目前的猜测是，0%结果更可能是环境漂移/钉顶不完整，而不是检查点故障。下一步一个好的做法是在一个尽可能与仓库路径对齐的新环境中重新测试，特别是：
> > > 
> > > * 蟒蛇`3.11.x`
> > > * `torch==2.5.1`， ， torchaudio==2.5.1 ''` torchvision==0.20.1`
> > > * `moojink/transformers-openvla-oft`在线上`4.40.1`
> > > * `tokenizers==0.19.1`
> > > * `huggingface-hub < 1.0`
> > > * MuJoCo`2.1.0` + `mujoco-py==2.1.2.14`
> > > * 干净重装`robosuite / robomimic / mimicgen / robosuite-task-zoo / LIBERO`
> > > * `PYTHONNOUSERSITE=1`以避免用户站点包对ConDA环境的影子
> > > 
> > > 尤其是，我认为MuJoCo的版本非常关键。如果有用的话，我也可以分享对我有效的安装脚本/环境摘要。
> > > <img alt="图片" width="1459" height="138" src="https://private-user-images.githubusercontent.com/232729665/581314712-c526f136-b6c5-474e-b93a-a0594194c9b0.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzcwODY0MzksIm5iZiI6MTc3NzA4NjEzOSwicGF0aCI6Ii8yMzI3Mjk2NjUvNTgxMzE0NzEyLWM1MjZmMTM2LWI2YzUtNDc0ZS1iOTNhLWEwNTk0MTk0YzliMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDQyNVQwMzAyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTgwY2Y3MmVhZjFiZDMzNDZhZDE3N2Q1YWRjNTY5ZWFiNmI5MDNkNzU2YjU0ZGJiMjE5Mjk1NDc4ODc0ZmVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.g6N9yNwE-P88LQac7mXCrfdHi-2JbZ4eLni2cyzdtmU"> <img alt="图片" width="1442" height="198" src="https://private-user-images.githubusercontent.com/232729665/581314713-4b61173d-2648-47da-9559-6c9d38c28d7f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzcwODY0MzksIm5iZiI6MTc3NzA4NjEzOSwicGF0aCI6Ii8yMzI3Mjk2NjUvNTgxMzE0NzEzLTRiNjExNzNkLTI2NDgtNDdkYS05NTU5LTZjOWQzOGMyOGQ3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDQyNVQwMzAyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDE2YmQ5MWY5ZTU4YzM1NDBkNzUyNGFjNTNkZmUxNDBkZTVjZGZmNjc3MDMyZDQzYTI3YmZkZjQ1Mzk5MjVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.Sfjap2FyAkZ6bhtAitq5xrnL6c5fblbzXqzd24pQKag">
> > 
> > 
> > 我又试了一次，还是0%。如果你能提供安装脚本/环境摘要，我觉得会很有帮助。
> > ```
> > python: 3.11.15 (main, Mar 11 2026, 17:20:07) [GCC 14.3.0]
> > python_executable: /root/miniconda3/envs/wmpo/bin/python
> > PYTHONNOUSERSITE: None
> > MUJOCO_PY_MUJOCO_PATH: /root/.mujoco/mujoco210
> > 
> > torch_cuda_available: True
> > torch_cuda_build: 12.4
> > gpu_name: NVIDIA H800 PCIe
> > gpu_capability: (9, 0)
> > 
> > torch: 2.5.1
> >   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/torch/__init__.py
> > torchvision: 0.20.1
> >   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/torchvision/__init__.py
> > torchaudio: 2.5.1
> >   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/torchaudio/__init__.py
> > transformers: 4.40.1
> >   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/transformers/__init__.py
> > tokenizers: 0.19.1
> >   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/tokenizers/__init__.py
> > huggingface-hub: 0.36.2
> >   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/huggingface_hub/__init__.py
> > numpy: 1.26.4
> >   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/numpy/__init__.py
> > tensorflow: 2.19.0
> >   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/tensorflow/__init__.py
> > tensorflow-datasets: 4.9.9
> >   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/tensorflow_datasets/__init__.py
> > timm: 0.9.10
> >   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/timm/__init__.py
> > peft: 0.11.0
> >   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/peft/__init__.py
> > diffusers: 0.33.0
> >   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/diffusers/__init__.py
> > xformers: 0.0.28.post3
> >   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/xformers/__init__.py
> > flash-attn: 2.5.5
> >   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/flash_attn/__init__.py
> > tensordict: 0.12.2
> >   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/tensordict/__init__.py
> > torchdata: 0.11.0
> >   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/torchdata/__init__.py
> > ray: 2.55.1
> >   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/ray/__init__.py
> > wandb: 0.26.1
> >   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/wandb/__init__.py
> > mujoco: 3.7.0
> >   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/mujoco/__init__.py
> > mujoco-py: 2.1.2.14
> >   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/mujoco_py/__init__.py
> > robosuite: 1.4.1
> >   path: /WMPO/dependencies/robosuite/robosuite/__init__.py
> > robomimic: 0.3.0
> >   path: /WMPO/dependencies/robomimic/robomimic/__init__.py
> > mimicgen: 1.0.0
> >   path: /WMPO/dependencies/mimicgen/mimicgen/__init__.py
> > robosuite_task_zoo: 0.1
> >   path: /WMPO/dependencies/robosuite-task-zoo/robosuite_task_zoo/__init__.py
> > colossalai: 0.4.7
> >   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/colossalai/__init__.py
> > tensornvme: 0.1.0
> >   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/tensornvme/__init__.py
> > apex: 0.1
> >   path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/apex/__init__.py
> > === end ===
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我在重新配置环境时注意到一个问题，似乎有两种 Mujoco：MuJoCo 2.1.0 + mujoco-py==2.1.2.14 和 mujoco：3.7.0。
> > ```
> > mujoco: 3.7.0 path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/mujoco/__init__.py 
> > mujoco-py: 2.1.2.14 path: /root/miniconda3/envs/wmpo/lib/python3.11/site-packages/mujoco_py/__init__.py
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 你是指“muJoco210 + mujoco-py： 2.1.2.14”，由“MuJoCo 2.1.0 + mujoco-py==2.1.2.14”吗？requirements.txt文件没有指定Mujoco的版本，当我运行时，它会自动安装。`pip install -r requirements.txt``mujoco: 3.7.0`
> 
> [install_superpod_full_wmpo.sh](https://github.com/user-attachments/files/27080779/install_superpod_full_wmpo.sh)
> 
> 谢谢——你最新的环境总结非常有帮助。
> 
> 是的：“MuJoCo 2.1.0 + mujoco-py==2.1.2.14”，我指的是在 解压的原生 MuJoCo 2.1.0 运行时，以及 Python 绑定。`~/.mujoco/mujoco210``mujoco-py==2.1.2.14`
> 
> 这与 PyPI 包是分开的。由于 不固定版本，确实可以安装更新的轮子，如 。所以，是的，一个环境可以包含以下两者：`mujoco``requirements.txt``mujoco``pip install -r requirements.txt``mujoco==3.7.0`
> 
> * 原生运行时：`~/.mujoco/mujoco210`
> * `mujoco-py==2.1.2.14`
> * 以及更新的 PyPI 软件包`mujoco`
> 
> 当我提到“MuJoCo 2.1.0”时，我指的是原生运行时，而不是由 报告的版本。`mujoco-py``import mujoco`
> 
> 供参考，下面是关键环境摘要和安装脚本（可能不适用于你，仅供参考），这些脚本是我生成非零结果的设置中产生的（咖啡P=128，P=1280）：`53.1%``73.4%`
> 
> === working WMPO environment summary ===
> python: 3.11.x
> PYTHONNOUSERSITE=1
> 
> torch==2.5.1
> torchvision==0.20.1
> torchaudio==2.5.1
> 
> transformers==4.40.1
> # installed from moojink/transformers-openvla-oft
> tokenizers==0.19.1
> huggingface-hub==0.31.1
> 
> numpy==1.26.4
> tensorflow==2.19.0
> timm==0.9.16
> peft==0.11.0
> diffusers==0.33.0
> xformers==0.0.28.post3
> flash-attn==2.5.5
> 
> MUJOCO_PY_MUJOCO_PATH=~/.mujoco/mujoco210
> LD_LIBRARY_PATH includes ~/.mujoco/mujoco210/bin
> native MuJoCo runtime: 2.1.0
> mujoco-py==2.1.2.14
> 
> editable dependencies:
> robosuite @ b9d8d3de5e3dfd1724f4a0e6555246c460407daa
> robomimic @ d0b37cf214bd24fb590d182edb6384333f67b661
> robosuite-task-zoo @ 74eab7f88214c21ca1ae8617c2b2f8d19718a9ed
> mimicgen (editable)
> LIBERO (editable)
> === end ===

Thank you very much!😊
I solved the problem after reinstalling moojink/transformers-openvla-oft and LIBERO.
<img width="905" height="191" alt="Image" src="https://github.com/user-attachments/assets/b4cfdb66-f54e-4178-92b7-4c1c019be248" />
This is the evaluate result of checkpoint_files/SFT_models/coffee, and it's finally not 0 anymore.😊
