### ISSUE TITLE
Task was killed due to the node running low on memory

### ISSUE THREAD

**Issue by OrangeSodahub** [WM-PO/WMPO#3]
Hi, I was running your codebase on A800 80G (single node 1 GPU, 14vCPU, 245GB MEM), with `torch2.5.1+cuda118`,  `xformers==0.0.28.post3`, `flash-attn==2.5.5`. However the process is always killed due to out of memeory. The detailed logs are as below:

```bash
(WorkerDict pid=395131) Step = 88                                                                                                                                                           
(WorkerDict pid=395131) Step = 96                                                                                                                                                           
(WorkerDict pid=395131) Step = 104                                                                                                                                                          
(WorkerDict pid=395131) Step = 112                                                                                                                                                          
Error executing job with overrides: ['+data.task_name=coffee', 'data.n_samples=8', 'data.filter_accuracy=True', 'data.accuracy_lower_bound=0.1', 'data.accuracy_upper_bound=0.9', 'data.over
sample_factor=1', 'data.train_batch_size=16', 'data.val_batch_size=16', 'data.max_prompt_length=256', 'data.max_response_length=128', '+data.rollout_batch_size=32', '+actor_rollout_ref.rol
lout_base_dir=./tmp_files/rollout_coffee_wmpo_128', 'actor_rollout_ref.model.path=./checkpoint_files/SFT_models/coffee', 'actor_rollout_ref.model.vla=openvla-oft', 'actor_rollout_ref.model
.action_token_len=7', 'actor_rollout_ref.model.action_chunks_len=8', 'actor_rollout_ref.actor.optim.lr=5e-6', 'actor_rollout_ref.actor.optim.warmup_style=constant', 'actor_rollout_ref.acto
r.ppo_mini_batch_size=32', 'actor_rollout_ref.actor.ppo_micro_batch_size=1', 'actor_rollout_ref.actor.use_dynamic_bsz=False', 'actor_rollout_ref.actor.fsdp_config.param_offload=False', 'ac
tor_rollout_ref.actor.fsdp_config.grad_offload=True', 'actor_rollout_ref.actor.fsdp_config.optimizer_offload=True', 'actor_rollout_ref.actor.grad_clip=1', 'actor_rollout_ref.actor.clip_rat
io_high=0.28', 'actor_rollout_ref.actor.clip_ratio_low=0.2', 'actor_rollout_ref.actor.num_images_in_input=1', 'actor_rollout_ref.actor.traj_mini_batch_size=4', 'actor_rollout_ref.model.ena
ble_gradient_checkpointing=False', 'actor_rollout_ref.model.use_remove_padding=False', 'actor_rollout_ref.actor.entropy_coeff=0.', 'actor_rollout_ref.rollout.num_images_in_input=1', 'actor
_rollout_ref.rollout.val_micro_batch_size=2', 'actor_rollout_ref.rollout.temperature=1.6', 'actor_rollout_ref.rollout.experiment_name=coffee_wmpo_128', 'actor_rollout_ref.rollout.micro_bat
ch_size=1', 'actor_rollout_ref.rollout.unnorm_key=coffee_d0_300_demos', 'actor_rollout_ref.rollout.model_family=openvla', 'actor_rollout_ref.rollout.num_steps_wait=10', 'actor_rollout_ref.
rollout.pretrained_checkpoint=./checkpoint_files/SFT_models/coffee', 'actor_rollout_ref.rollout.center_crop=True', 'actor_rollout_ref.rollout.max_prompt_length=512', 'actor_rollout_ref.rol
lout.log_prob_micro_batch_size=4', 'actor_rollout_ref.rollout.tensor_model_parallel_size=1', 'actor_rollout_ref.rollout.name=hf', 'actor_rollout_ref.rollout.gpu_memory_utilization=0.9', 'a
ctor_rollout_ref.ref.log_prob_micro_batch_size=4', 'actor_rollout_ref.ref.fsdp_config.param_offload=True', 'actor_rollout_ref.wm.inference_config_path=./checkpoint_files/world_models/coffe
e/P_128/inference_cfg.py', 'actor_rollout_ref.wm.train_config_path=./checkpoint_files/world_models/coffee/P_128/train_mimicgen_cfg.py', '+actor_rollout_ref.wm.update_wm=False', 'actor_roll
out_ref.wm.reward_model_path=./checkpoint_files/reward_models/videomae_coffee.pth', 'actor_rollout_ref.wm.rm_threshold=0.82', 'actor_rollout_ref.wm.rm_img_size=224', '+actor_rollout_ref.wm
.rm_lr=1e-4', '+actor_rollout_ref.wm.rm_batch_size=4', '+actor_rollout_ref.wm.rm_val_batch_size=32', '+actor_rollout_ref.wm.rm_num_workers=8', '+actor_rollout_ref.wm.wm_training_steps_per_
epoch=10000', '+actor_rollout_ref.wm.rm_training_steps_per_epoch=10000', 'actor_rollout_ref.wm.enable=True', 'algorithm.kl_ctrl.kl_coef=0.00', '+trainer.rollout_before_train=False', 'train
er.logger=[console,wandb]', 'trainer.project_name=WMPO-mimicgen', 'trainer.experiment_name=coffee_wmpo_128', 'trainer.default_local_dir=./checkpoint_files/WMPO-mimicgen/coffee_wmpo_128', '
trainer.n_gpus_per_node=1', 'trainer.nnodes=1', 'trainer.save_freq=1', 'trainer.test_freq=1', 'trainer.total_epochs=100', 'trainer.val_only=False', '+trainer.sim_rollout_epoch=1', 'algorit
hm.adv_estimator=grpo', 'algorithm.adv_params.verifier_gamma=1.0', 'algorithm.adv_params.reward_model_gamma=1.0', 'trainer.runtime_env=./align.json', 'trainer.wandb_mode=online', 'trainer.
val_before_train=True']                                                                                                                                                                     
(raylet) A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. Lease ID: 000000009a221a083eb58b
af2b5f867c3b9aa430c9e9cd9d4f36266ab1f9c1a7 Worker ID: 7d51819e037f74093b70a888bbd90c7518169c098880b8bfc4169f89 Node ID: 8289f87b78d161ae21bf723c7c57838345a56248dd48a2c3f0d5ac73 Worker IP a
ddress: 172.24.0.226 Worker port: 36245 Worker PID: 395131 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. Some co
mmon causes include: (1) the process was killed by the OOM killer due to high memory usage, (2) ray stop --force was called, or (3) the worker crashed unexpectedly due to SIGSEGV or anothe
r unexpected error.                                                                                                                                                                         
(raylet) [2025-12-07 09:57:19,206 E 393463 393463] (raylet) node_manager.cc:3277: 2 Workers (tasks / actors) killed due to memory pressure (OOM), 0 Workers crashed due to other reasons at 
node (ID: 8289f87b78d161ae21bf723c7c57838345a56248dd48a2c3f0d5ac73, IP: 172.24.0.226) over the last time period. To see more information about the Workers killed on this node, use `ray log
s raylet.out -ip 172.24.0.226`                                                                                                                                                              
(raylet)                                                                                                                                                                                    
(raylet) Refer to the documentation on how to address the out of memory issue: https://docs.ray.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory 
on this node or reducing task parallelism by requesting more CPUs per task. To adjust the kill threshold, set the environment variable `RAY_memory_usage_threshold` when starting Ray. To di
sable worker killing, set the environment variable `RAY_memory_monitor_refresh_ms` to zero.                                                                                                 
Traceback (most recent call last):                                                                                                                                                          
  File "<frozen runpy>", line 198, in _run_module_as_main                                                                                                                                   
  File "<frozen runpy>", line 88, in _run_code
  .......
  File "~/.conda/envs/wmpo/lib/python3.11/site-packages/ray/_private/worker.py", line 1033, in get_objects
    raise value
ray.exceptions.OutOfMemoryError: Task was killed due to the node running low on memory.
Memory on the node (IP: 172.24.0.226, ID: 8289f87b78d161ae21bf723c7c57838345a56248dd48a2c3f0d5ac73) where the lease (actor ID: NIL_IDlease ID: 0000000001000000fffffffffffffffffffffffffffff
fffffffffffffffffff, name=main_task, pid=394337, memory used=1.32GB) was running was 215.90GB / 227.12GB (0.950565), which exceeds the memory usage threshold of 0.95. Ray killed this worke
r (ID: e168075f6039993c2fb471b0a333f5142b9c3c01324242d815607733) because it was the most recently scheduled task; to see more information about memory usage on this node, use `ray logs ray
let.out -ip 172.24.0.226`. To see the logs of the worker, use `ray logs worker-e168075f6039993c2fb471b0a333f5142b9c3c01324242d815607733*out -ip 172.24.0.226. Top 10 memory users:
PID     MEM(GB) COMMAND
395131  6.50
416297  3.77    cicc --c++17 --gnu_version=90400 --display_error_number --orig_src_file_name /tmp/pip-install-y6smmx...
416303  3.76    cicc --c++17 --gnu_version=90400 --display_error_number --orig_src_file_name /tmp/pip-install-y6smmx...
416285  3.69    cicc --c++17 --gnu_version=90400 --display_error_number --orig_src_file_name /tmp/pip-install-y6smmx...
416204  3.65    cicc --c++17 --gnu_version=90400 --display_error_number --orig_src_file_name /tmp/pip-install-y6smmx...
416240  3.64    cicc --c++17 --gnu_version=90400 --display_error_number --orig_src_file_name /tmp/pip-install-y6smmx...
416258  3.61    cicc --c++17 --gnu_version=90400 --display_error_number --orig_src_file_name /tmp/pip-install-y6smmx...
416271  3.60    cicc --c++17 --gnu_version=90400 --display_error_number --orig_src_file_name /tmp/pip-install-y6smmx...
416187  3.60    cicc --c++17 --gnu_version=90400 --display_error_number --orig_src_file_name /tmp/pip-install-y6smmx...
416222  3.59    cicc --c++17 --gnu_version=90400 --display_error_number --orig_src_file_name /tmp/pip-install-y6smmx...
Refer to the documentation on how to address the out of memory issue: https://docs.ray.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory on this n
ode or reducing task parallelism by requesting more CPUs per task. To adjust the kill threshold, set the environment variable `RAY_memory_usage_threshold` when starting Ray. To disable wor
ker killing, set the environment variable `RAY_memory_monitor_refresh_ms` to zero.
I1207 09:57:45.796000 392551 site-packages/torch/_dynamo/utils.py:399] TorchDynamo compilation metrics:
I1207 09:57:45.796000 392551 site-packages/torch/_dynamo/utils.py:399] Function, Runtimes (s)
V1207 09:57:45.799000 392551 site-packages/torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats constrain_symbol_range: CacheInfo(hits=0, misses=0, maxsize=None, currsize=0)
V1207 09:57:45.801000 392551 site-packages/torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats evaluate_expr: CacheInfo(hits=0, misses=0, maxsize=256, currsize=0)
V1207 09:57:45.801000 392551 site-packages/torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats _simplify_floor_div: CacheInfo(hits=0, misses=0, maxsize=None, currsize=0)
V1207 09:57:45.802000 392551 site-packages/torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats _maybe_guard_rel: CacheInfo(hits=0, misses=0, maxsize=256, currsize=0)
V1207 09:57:45.802000 392551 site-packages/torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats _find: CacheInfo(hits=0, misses=0, maxsize=None, currsize=0)
V1207 09:57:45.802000 392551 site-packages/torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats has_hint: CacheInfo(hits=0, misses=0, maxsize=256, currsize=0)
V1207 09:57:45.803000 392551 site-packages/torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats size_hint: CacheInfo(hits=0, misses=0, maxsize=256, currsize=0)
V1207 09:57:45.803000 392551 site-packages/torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats simplify: CacheInfo(hits=0, misses=0, maxsize=None, currsize=0)
V1207 09:57:45.803000 392551 site-packages/torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats _update_divisible: CacheInfo(hits=0, misses=0, maxsize=None, currsize=0)
V1207 09:57:45.804000 392551 site-packages/torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats replace: CacheInfo(hits=0, misses=0, maxsize=None, currsize=0)
V1207 09:57:45.804000 392551 site-packages/torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats _maybe_evaluate_static: CacheInfo(hits=0, misses=0, maxsize=None, currsize=0)
V1207 09:57:45.804000 392551 site-packages/torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats get_implications: CacheInfo(hits=0, misses=0, maxsize=None, currsize=0)
V1207 09:57:45.804000 392551 site-packages/torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats get_axioms: CacheInfo(hits=0, misses=0, maxsize=None, currsize=0)
V1207 09:57:45.805000 392551 site-packages/torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats safe_expand: CacheInfo(hits=0, misses=0, maxsize=256, currsize=0)
V1207 09:57:45.805000 392551 site-packages/torch/fx/experimental/symbolic_shapes.py:122] lru_cache_stats uninteresting_files: CacheInfo(hits=0, misses=0, maxsize=None, currsize=0)
```

I would like to know:
Have you encountered this issue?
Which part of environment setup I have missed?
Thanks!

**Comment by OrangeSodahub** [comment]
@fangqi-Zhu Sorry, I found no lines were updated exactly, can you check that again?

**Comment by fangqi-Zhu** [comment]
Thanks for reporting this! We have fixed the issue, and our code has been tested on H100 and A100 GPUs.

This issue is caused by the default dataprotobuf serialization method. As a temporary workaround, you can fix the bug by setting the following environment variable:

```bash
export VERL_DATAPROTO_SERIALIZATION_METHOD=numpy

**Comment by OrangeSodahub** [comment]
@fangqi-Zhu Thanks for your help!

However after I update the codes and set `VERL_DATAPROTO_SERIALIZATION_METHOD`, OOM issue still exist.

I’m running on 4 × 48 GB GPUs, so I set `data.n_samples=4` and reduced all other batch size parameters by half.
Which part could be triggering this issue? Should I be using 8 GPUs instead of 4, or is there a recommended way to set n_samples?

**Comment by WM-PO** [comment]
@OrangeSodahub Thanks for your interest in our work!

This issue is caused by insufficient system RAM, not GPU memory. Ray is killing the worker due to node-level memory pressure, and from the logs there appear to be multiple processes consuming a large amount of host memory:

> PID     MEM(GB) COMMAND
395131  6.50
416297  3.77    cicc --c++17 --gnu_version=90400 --display_error_number --orig_src_file_name /tmp/pip-install-y6smmx...
416303  3.76    cicc --c++17 --gnu_version=90400 --display_error_number --orig_src_file_name /tmp/pip-install-y6smmx...
416285  3.69    cicc --c++17 --gnu_version=90400 --display_error_number --orig_src_file_name /tmp/pip-install-y6smmx...
416204  3.65    cicc --c++17 --gnu_version=90400 --display_error_number --orig_src_file_name /tmp/pip-install-y6smmx...
416240  3.64    cicc --c++17 --gnu_version=90400 --display_error_number --orig_src_file_name /tmp/pip-install-y6smmx...
416258  3.61    cicc --c++17 --gnu_version=90400 --display_error_number --orig_src_file_name /tmp/pip-install-y6smmx...
416271  3.60    cicc --c++17 --gnu_version=90400 --display_error_number --orig_src_file_name /tmp/pip-install-y6smmx...
416187  3.60    cicc --c++17 --gnu_version=90400 --display_error_number --orig_src_file_name /tmp/pip-install-y6smmx...
416222  3.59    cicc --c++17 --gnu_version=90400 --display_error_number --orig_src_file_name /tmp/pip-install-y6smmx... 

Could you please check the node’s RAM usage during training, terminate unnecessary processes, and try to increase system memory budget if possible?
